In [1]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers, activations
from tensorflow.keras.layers import Dense 
import numpy as np

In [2]:
gpus = tf.config.list_physical_devices('GPU')
if gpus:
  # Restrict TensorFlow to only allocate 1GB of memory on the first GPU
  try:
    tf.config.set_logical_device_configuration(
        gpus[0],
        [tf.config.LogicalDeviceConfiguration(memory_limit=1024)])
    logical_gpus = tf.config.list_logical_devices('GPU')
    print(len(gpus), "Physical GPUs,", len(logical_gpus), "Logical GPUs")
  except RuntimeError as e:
    # Virtual devices must be set before GPUs have been initialized
    print(e)

1 Physical GPUs, 1 Logical GPUs


In [3]:
input = np.array([np.random.randint(50,100,5),
         np.random.randint(0,50,5),
         np.random.randint(0,50,5),
         np.random.randint(50,100,5),
         np.random.randint(50,100,5),
         np.random.randint(0,50,5),
         np.random.randint(50,100,5)])
output = np.array([10,0,0,10,10,0,10])
input,output

(array([[72, 81, 87, 66, 60],
        [17, 41, 23, 47, 10],
        [31, 11,  2, 14,  2],
        [52, 52, 92, 66, 54],
        [54, 88, 62, 58, 78],
        [47, 44, 41, 32, 17],
        [60, 51, 95, 62, 97]]),
 array([10,  0,  0, 10, 10,  0, 10]))

In [4]:
Input = layers.InputLayer([5])


In [5]:
S = keras.Sequential([Input,
                      Dense(64, activations.selu),
                      Dense(64, activations.selu),
                      Dense(1, activations.linear)
                     ])

In [6]:
S.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 64)                384       
                                                                 
 dense_1 (Dense)             (None, 64)                4160      
                                                                 
 dense_2 (Dense)             (None, 1)                 65        
                                                                 
Total params: 4,609
Trainable params: 4,609
Non-trainable params: 0
_________________________________________________________________


In [7]:
S.compile(loss=keras.losses.Hinge())

In [8]:
S.fit(input,output, epochs=10, verbose=1)

S(input)

Epoch 1/10
1/1 [==============================] - 2s 2s/step - loss: 0.4286
Epoch 2/10
1/1 [==============================] - 0s 11ms/step - loss: 0.4286
Epoch 3/10
1/1 [==============================] - 0s 11ms/step - loss: 0.4286
Epoch 4/10
1/1 [==============================] - 0s 9ms/step - loss: 0.4286
Epoch 5/10
1/1 [==============================] - 0s 11ms/step - loss: 0.4286
Epoch 6/10
1/1 [==============================] - 0s 10ms/step - loss: 0.4286
Epoch 7/10
1/1 [==============================] - 0s 14ms/step - loss: 0.4286
Epoch 8/10
1/1 [==============================] - 0s 15ms/step - loss: 0.4286
Epoch 9/10
1/1 [==============================] - 0s 10ms/step - loss: 0.4286
Epoch 10/10
1/1 [==============================] - 0s 13ms/step - loss: 0.4286


<tf.Tensor: shape=(7, 1), dtype=float32, numpy=
array([[ 7.1973267],
       [ 4.8686085],
       [-2.2795293],
       [ 6.7417965],
       [ 8.19239  ],
       [ 0.8099861],
       [ 4.212105 ]], dtype=float32)>